@extends('admin.layout')

@section('admin_kicker', 'Payments')
@section('admin_title', 'Payment ledger')
@section('admin_subtitle', 'Monitor confirmed transactions tied to live checkout activity across the storefront.')

@section('content')
    <section class="admin-stats-grid">
        <article class="admin-card admin-stat-card">
            <span class="admin-icon"><i class="fa fa-credit-card"></i></span>
            <div class="admin-muted">Payments</div>
            <div class="admin-stat-value">{{ number_format($stats['total']) }}</div>
            <div class="admin-stat-foot">Successful payment records in the system</div>
        </article>

        <article class="admin-card admin-stat-card">
            <span class="admin-icon"><i class="fa fa-money"></i></span>
            <div class="admin-muted">Revenue</div>
            <div class="admin-stat-value">Rs. {{ number_format((float) $stats['revenue'], 2) }}</div>
            <div class="admin-stat-foot">Captured from online payment flow</div>
        </article>

        <article class="admin-card admin-stat-card">
            <span class="admin-icon"><i class="fa fa-sun-o"></i></span>
            <div class="admin-muted">Today</div>
            <div class="admin-stat-value">Rs. {{ number_format((float) $stats['today'], 2) }}</div>
            <div class="admin-stat-foot">Revenue received since midnight</div>
        </article>

        <article class="admin-card admin-stat-card">
            <span class="admin-icon"><i class="fa fa-user-circle-o"></i></span>
            <div class="admin-muted">Paying Customers</div>
            <div class="admin-stat-value">{{ number_format($stats['customers']) }}</div>
            <div class="admin-stat-foot">Unique customers with payment records</div>
        </article>
    </section>

    <section class="admin-card">
        <div class="admin-card-head">
            <div>
                <h3 class="admin-card-title">Recent Payments</h3>
                <div class="admin-muted">Transactions generated by the storefront checkout flow</div>
            </div>
        </div>

        <div class="admin-table-wrap">
            <table class="admin-table">
                <thead>
                    <tr>
                        <th>Transaction</th>
                        <th>Customer</th>
                        <th>Product</th>
                        <th>Amount</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($payments as $payment)
                        <tr>
                            <td>
                                <strong>{{ $payment->transaction_id }}</strong>
                                <div class="admin-muted">{{ $payment->currency ?: 'USD' }}</div>
                            </td>
                            <td>
                                <div>{{ $payment->user?->name ?? 'Guest / removed user' }}</div>
                                <div class="admin-muted">{{ $payment->user?->email ?? 'No email available' }}</div>
                            </td>
                            <td>
                                <div>{{ $payment->product?->title ?? 'Archived product' }}</div>
                                <div class="admin-muted">{{ $payment->product?->category ?? 'Uncategorized' }}</div>
                            </td>
                            <td>Rs. {{ number_format((float) $payment->amount, 2) }}</td>
                            <td>{{ optional($payment->payment_date)->format('d M Y h:i A') ?? optional($payment->created_at)->format('d M Y h:i A') }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="admin-muted">No payment records available yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </section>
@endsection
